import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import TanstackInitializer from './TanstackInitializer'
import ThemeProvider from './providers/ThemeProvider'
import MswInitializer from './MswInitializer'

const notoSansKR = Noto_Sans_KR({
  weight: ['300', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-noto-sans-kr',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      {/* 부드럽게 보이도록 안티앨리어싱 처리 */}
      <body className={`${notoSansKR.className} antialiased`}>
        <MswInitializer>
          <TanstackInitializer>
            <ThemeProvider>{children}</ThemeProvider>
          </TanstackInitializer>
        </MswInitializer>
      </body>
    </html>
  )
}
