import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import TanstackInitializer from './TanstackInitializer'
import ThemeProvider from './_providers/ThemeProvider'
import MswInitializer from './MswInitializer'
import { PropsWithChildren } from 'react'
import DataFetchProvider from '@providers/DataFetchProvider'

const notoSansKR = Noto_Sans_KR({
  weight: ['300', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-noto-sans-kr',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Layout = ({ children }: PropsWithChildren) => {
  return <div className="pt-header">{children}</div>
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const enableMsw = process.env.NEXT_PUBLIC_ENABLE_MSW === 'true'

  return (
    <html lang="ko">
      {/* 부드럽게 보이도록 안티앨리어싱 처리 */}
      <body className={`${notoSansKR.className} antialiased`}>
        <Layout>
          {enableMsw ? (
            <MswInitializer>
              <TanstackInitializer>
                <ThemeProvider>
                  <DataFetchProvider>{children}</DataFetchProvider>
                </ThemeProvider>
              </TanstackInitializer>
            </MswInitializer>
          ) : (
            <TanstackInitializer>
              <ThemeProvider>
                <DataFetchProvider>{children}</DataFetchProvider>
              </ThemeProvider>
            </TanstackInitializer>
          )}
        </Layout>
      </body>
    </html>
  )
}
